---
# tasks file for apache2
- name: install web components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - apache2
  - libapache2-mod-wsgi

- name: ensure mod_wsgi enabled
  apache2_module:
    name: wsgi
    state: present
  notify: restart apache2

- name: deactivate default apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: ensure apache2 running
  service:
    name: apache2
    state: started
    enabled: yes
