---
# tasks file for mysql
- name: install mysql-server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: install tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - python-mysqldb

- name: ensure mysql listening on private IP only
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: ^bind-address
#    line: "bind-address               = 0.0.0.0"
    line: "bind-address               = {{ ansible_eth1.ipv4.address }}"
    state: present
    backup: yes
  notify: restart mysql

- name: ensure mysql running
  service:
    name: mysql
    state: started
    enabled: yes

- name: create database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: create mysql user
  mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ db_user_host }}"
    state: present
