---
# Hosts section
- hosts: LoadBalancers

# Tasks section
  tasks:

  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: ensure nginx running
#    service:
    systemd:
      name: nginx
      state: started
      enabled: yes

  - name: configure nginx site
    template:
      src: ../templates/nginx.conf.j2
      dest: /etc/nginx/sites-available/demo
      mode: 0644
    notify: restart nginx

  - name: deactivate default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: activate demo nginx site
    file:
      src: /etc/nginx/sites-available/demo
      dest: /etc/nginx/sites-enabled/demo
      state: link
    notify: restart nginx

# Handlers section
  handlers:

  - name: restart nginx
#    service:
    systemd:
      name: nginx
      state: restarted






