---

- hosts: LoadBalancers

  tasks:

  - name: verify nginx service
    command: service nginx status

  - name: verify nginx is listening on port 80
    wait_for:
      port: 80
      timeout: 1

# ----

- hosts: WebServers

  tasks:

  - name: verify apache2 service
    command: service apache2 status

  - name: verify apache2 is listening on port 80
    wait_for:
      port: 80
      timeout: 1

# ----

- hosts: DBServers

  tasks:

  - name: verify mysql service
    command: service mysql status

  - name: verify mysql is listening on port 3306
    wait_for:
      port: 3306
      timeout: 1

# ----

- hosts: control

  tasks:

  - name: verify end-to-end response
    uri:
      url: http://{{ item }}
      return_content: yes
    with_items:
    - "{{ groups['LoadBalancers'] }}"
    register: lb_index

  - fail:
      msg: "Index failed to return correct content"
    when: "'Hello, from sunny' not in item.content"
    with_items:
    - "{{ lb_index.results }}"

  - name: verify db response
    uri:
      url: http://{{ item }}/db
      return_content: yes
    with_items:
    - "{{ groups['LoadBalancers'] }}"
    register: lb_db

  - fail:
      msg: "DB failed to return correct content"
    when: "'Database Connected from' not in item.content"
    with_items:
    - "{{ lb_db.results }}"

# ----

- hosts: LoadBalancers

  tasks:

  - name: verify backend response
    uri:
      url: http://{{ item }}
      return_content: yes
    with_items:
    - "{{ groups['WebServers'] }}"
    register: app_index

  - fail:
      msg: "Index failed to return correct content"
# Commented out, as my actual hostnames don't match the inventory, which makes
# the check below fail.
#    when: "'Hello, from sunny {{ item.item }}!' not in item.content"
    when: "'Hello, from sunny' not in item.content"
    with_items:
    - "{{ app_index.results }}"

  - name: verify backend db response
    uri:
      url: http://{{ item }}/db
      return_content: yes
    with_items:
    - "{{ groups['WebServers'] }}"
    register: app_db

  - fail:
      msg: "DB failed to return correct content"
    when: "'Database Connected from' not in item.content"
    with_items:
    - "{{ app_db.results }}"




